name: LangChat
main: me.jtghawk137.langchat.LangChat
author: JTGhawk137
description: Language learning chat plugin
version: 1.0.0
commands:
    lang:
        description: Set your language learning preferences
        usage: /<command>