name: LangChat
main: me.jtghawk137.langchat.LangChat
author: JTGhawk137
description: Language learning chat plugin
version: 1.0.0
commands:
    test:
        description: Test GUI's
        usage: /<command>